### ISSUE TITLE
Adding a DomainLocaleGuesser?

### ISSUE THREAD

**Issue by coudenysj** [lunetics/LocaleBundle#141]
Hi,

A client wants to have multiple .be domains to differentiate between Dutch and French versions of the website. I see that only `SubdomainLocaleGuesser` and `TopleveldomainLocaleGuesser` are available.

Would you like me to write a `DomainLocaleGuesser` and put it in a PR? Or should I just add it to the project as a custom guesser?

**Comment by lunetics** [comment]
Hey @coudenysj sure we appreciate it having more guessers to be flexible and of course it would be a nice addition to the bundle. Just go ahead and make a PR, i'l merge it then and release a new minor version

Cheers
