### ISSUE TITLE
Wrong dev-master version on packagist

### ISSUE THREAD

**Issue by JHGitty** [lunetics/LocaleBundle#158]
https://packagist.org/packages/lunetics/locale-bundle

There are versions ``v2.3.1``, ``v2.4.0`` and ``v2.4.1``.

So why is there ``dev-master/2.3.x-dev`` and not ``dev-master/2.4.x-dev``?

**Comment by dbu** [comment]
that sounds wrong, it should be 2.4.x-dev then (until there are changes that bump the version to 2.5.x-dev)

**Comment by JHGitty** [comment]
ping @dbu @lsmith77 @lunetics @ikwattro

**Comment by ikwattro** [comment]
@dbu @lunetics are you already busy with a PR for changing dev-master in composer ?

**Comment by dbu** [comment]
not me. https://github.com/lunetics/LocaleBundle/compare/2.4.1...master looks like there are no important changes yet, so the alias can be for 2.4 for now imho.

**Comment by ikwattro** [comment]
Ok I'll make a PR for 2.4.x-dev as alias

**Comment by JHGitty** [comment]
See #162

**Comment by dbu** [comment]
fixed by #162
