### ISSUE TITLE
DEPRECATED

### ISSUE THREAD

**Issue by tubssp** [lunetics/LocaleBundle#165]
Symfony 2.7

DEPRECATED - The "pattern" option in file "/symfony/vendor/lunetics/locale-bundle/Lunetics/LocaleBundle/Resources/config/routing.yml" is deprecated since version 2.2 and will be removed in 3.0. Use the "path" option in the route definition instead. -

    Called from YamlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 45
    Called from DelegatingLoader::load() at line 76
    Called from DelegatingLoader::load() at line 54
    Called from Router::getRouteCollection() at line 373
    Called from Router::getMatcherDumperInstance() at line 288
    Called from Router::Symfony\Component\Routing\{closure}()
    Called from call_user_func() at line 46
    Called from ConfigCacheFactory::cache() at line 302
    Called from Router::getMatcher() at line 250
    Called from Router::matchRequest() at line 137
    Called from RouterListener::onKernelRequest()
    Called from call_user_func() at line 61
    Called from WrappedListener::__invoke()
    Called from call_user_func() at line 164
    Called from EventDispatcher::doDispatch() at line 53
    Called from EventDispatcher::dispatch() at line 167
    Called from ContainerAwareEventDispatcher::dispatch() at line 124
    Called from TraceableEventDispatcher::dispatch() at line 3083
    Called from HttpKernel::handleRaw() at line 3056
    Called from HttpKernel::handle() at line 3207
    Called from ContainerAwareHttpKernel::handle() at line 2429
    Called from Kernel::handle() at line 30

**Comment by caramba1337** [comment]
There is already a PR #166
