### ISSUE TITLE
Easy locale switcher with route parameter _locale?

### ISSUE THREAD

**Issue by JHGitty** [lunetics/LocaleBundle#177]
I want to create a route which is exactly the same route with same parameters except that I like to change the "_locale" parameter.

This issue / question is similar to https://github.com/KnpLabs/KnpMenuBundle/issues/288.

Does anybody have an idea how to get exactly the same route but with changed locale? Maybe there is any easy way in combination with the Switcher of this bundle?

In Twig I could do this:
```twig
<a href="{{ path(app.request.get('_route'), app.request.get('_route_params')|merge({'_locale': 'fr'})) }}">Test</a>
```

But I like to do it in PHP.

**Comment by dbu** [comment]
your logic is basically what TargetInformationBuilder is doing.

i guess you could write your own twig extension that accepts the request
and the new locale. but i don't think it would belong into this bundle,
as the language switcher uses the TargetInformationBuilder and you can't
give it your own URL.

**Comment by JHGitty** [comment]
The most important thing for me is to create the same route with changed locale in the menu builder of KnpMenuBundle as you can see in the issue https://github.com/KnpLabs/KnpMenuBundle/issues/288.

That because I need the same route with changed _locale in PHP and not in Twig.

**Comment by dbu** [comment]
@lunetics is the owner of this, lets see what he thinks.

**Comment by jonny827** [comment]
@JHGitty  Is this what you are looking for?

`$menu->addChild('Test', array('route' => 'test', 'routeParameters' => array('_locale' => 'fr')));`

Modified an example in the KNPMenuBundle doc's found [here](https://github.com/KnpLabs/KnpMenuBundle/blob/master/Resources/doc/index.rst) to meet your needs.
