### ISSUE TITLE
Support for Symfony3

### ISSUE THREAD

**Issue by JHGitty** [lunetics/LocaleBundle#178]
Is this bundle ready for Symfony3? Is it working on Symfony 3.0.0-BETA1?

**Comment by JHGitty** [comment]
This issue is blocked by:
1. https://github.com/lunetics/LocaleBundle/issues/176
2. https://github.com/lunetics/LocaleBundle/issues/175

**Comment by Ma27** [comment]
not sure whether I have enough time, but I may have a look at it tonight...

**Comment by dbu** [comment]
fixed in #179
