### ISSUE TITLE
Installing within Symfony 3.1 fails

### ISSUE THREAD

**Issue by fkrauthan** [lunetics/LocaleBundle#186]
I try to install the bundle with symfony 3.1 (`composre require lunetics/locale-bundle`).
But I get some dependency conflicts:

```
  Problem 1
    - Installation request for lunetics/locale-bundle ^2.5 -> satisfiable by lunetics/locale-bundle[2.5.1].
    - Conclusion: remove symfony/symfony v3.1.0
    - Conclusion: don't install symfony/symfony v3.1.0
    - lunetics/locale-bundle 2.5.1 requires symfony/locale ^2.8|^3.0 -> satisfiable by symfony/locale[v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7].
    - symfony/locale v2.8.0 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7].
    - symfony/locale v2.8.1 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7].
    - symfony/locale v2.8.2 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7].
    - symfony/locale v2.8.3 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7].
    - symfony/locale v2.8.4 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7].
    - symfony/locale v2.8.5 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7].
    - symfony/locale v2.8.6 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7].
    - symfony/locale v2.8.7 requires symfony/intl ~2.7|~3.0.0 -> satisfiable by symfony/intl[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7].
    - don't install symfony/intl v2.7.0|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.1|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.10|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.11|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.12|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.13|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.14|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.2|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.3|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.4|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.5|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.6|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.7|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.8|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.7.9|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.0|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.1|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.2|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.3|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.4|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.5|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.6|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v2.8.7|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.0|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.1|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.2|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.3|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.4|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.5|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.6|don't install symfony/symfony v3.1.0
    - don't install symfony/intl v3.0.7|don't install symfony/symfony v3.1.0
    - Installation request for symfony/symfony 3.1.* -> satisfiable by symfony/symfony[v3.1.0].
```

Any idea how I can resolve that or if you could create a version that runs with Symfony 3.1?

**Comment by dbu** [comment]
this is odd. you should require the locale bundle ^2.4.0 because there is no 2.5 and even master is not aliased to 2.5. no idea why there exists a https://packagist.org/packages/lunetics/locale-bundle#2.5.1 on packagist. @lunetics did you accidentally tag that and delete the tag again?

but according to packagist, all dependencies in composer.json are specified as ^2.8|^3.0 so i still don't get why this does not resolve to anything. does intl 3.0 not allow symfony 3.1 or something like that?

**Comment by dbu** [comment]
ah, also discussed in a merged merge request #179 . @jonnnnyw found a workaround:

It turns out it's the `symfony/locale` bundle causing this. The [2.8.7 ](https://github.com/symfony/locale/blob/v2.8.7/composer.json) tag only supports `symfony/intl` 3.0.*.

The master branch however supports 3.* so you can alias the `symfony/locale` master branch as 2.8.7 to get around this. This isn't a huge deal as the `symfony/locale` package is deprecated anyway so I assume it is going to be removed from this bundle at some point.

```
"require": {
        "symfony/symfony": "~3.1",
        "symfony/locale": "dev-master as 2.8.7"
        ...
```

**Comment by dbu** [comment]
i found no issue on symfony/symfony about this. not sure what should happen at this point. maybe we just have to wait for the next release of symfony/locale...

**Comment by fkrauthan** [comment]
@dbu Do you think that removing the dependency to smyfony locale is something that is gonna happen soon? I rather not have deprecated code run in my system

**Comment by jonnnnyw** [comment]
The symfony locale component only contains 1 class. It's more of a proxy for the intl component. You could just bundle it into this library if you really do need it and drop the dependency.

**Comment by Tobion** [comment]
There is something strange: 
- https://github.com/symfony/locale/blob/master/composer.json#L20: "symfony/intl": "~2.7|~3.0"
- https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Locale/composer.json#L20: "symfony/intl": "~2.7|~3.0.0"

But the master branch of symfony/locale will never be released (as it's removed in 3.0) and I don't see how it changed there at all. And in 2.8 it doesn't allow >=3.1. So I guess the 2.8 has to be fixed.

**Comment by dbu** [comment]
thanks. https://github.com/symfony/symfony/pull/18995

is locale deprecated? what should we use instead?

**Comment by jonnnnyw** [comment]
> The symfony locale component only contains 1 class. It's more of a proxy for the intl component. You could just bundle it into this library if you really do need it and drop the dependency.

**Comment by dbu** [comment]
well, if symfony decided to drop it, there might something else that is the new state of the art to solve what we solved with symfony/locale before. i am not too fond of copying code, unless we are sure why we need to do it.

**Comment by stof** [comment]
As explained in the deprecation message, use methods of the ``Symfony\Component\Intl\Intl`` class instead, which achieve similar use cases (and gives more power to achieve other use cases).

**Comment by jonnnnyw** [comment]
The intl component is what replaces it. I assumed the moved all of the logic out of the locale component and just left the interface for backwards compatibility. Take a look at the [remaining class](https://github.com/symfony/locale/blob/master/Locale.php). It's just a proxy for the intl component.

**Comment by stof** [comment]
@dbu FYI, https://github.com/lunetics/LocaleBundle/blob/master/Switcher/TargetInformationBuilder.php is *already* using the new API. I haven't found any usage of the deprecated class from ``symfony/locale``. It looks like the requirement is actually useless and should be removed.

**Comment by lunetics** [comment]
The question is, do we need the symfony/intl class at all, since it only provides an layer for the "en" language. Maybe make the php intl extension as requirement and ditch symfony/intl?

**Comment by stof** [comment]
@lunetics no. symfony/intl provides the ext-intl stub for the en language, but it also provides additional ICU data not exposed in ext-intl, and these are for all locales. When using the ``Intl`` class, you are accessing these additional data
