### ISSUE TITLE
Symfony 4.0 compatibility

### ISSUE THREAD

**Issue by mkalisz77** [lunetics/LocaleBundle#190]
In routing.yml %locale% must be quoted due to this depreciation message:
User Deprecated: Not quoting the scalar "%locale%" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0.

lunetics_locale_switcher:
    path: /changeLocale/{_locale}
    defaults:
        _controller: lunetics_locale.switcher_controller:switchAction
        _locale: %locale%

**Comment by dbu** [comment]
fixed in #191, #195 adds tests for symfony 4
