### ISSUE TITLE
Circular reference `lunetics_locale.twig.switcher`

### ISSUE THREAD

**Issue by michalbundyra** [lunetics/LocaleBundle#206]
Since this change: https://github.com/lunetics/LocaleBundle/commit/ef42343341c59386efae05fd5692913d7ef5a01d
and release 2.6 I have an issue with Circular reference in my symfony application. Everything works fine on version 2.5.4.

When `twig` (`templating` service) is loading, it loads also all extension, and I'm getting 500 error:
```
Circular reference detected for service "templating", path: "templating -> twig -> lunetics_locale.twig.switcher -> lunetics_locale.switcher_helper".
```

How can I resolve that issue?

**Comment by botjaeger** [comment]
Any updates here?

**Comment by dbu** [comment]
@ElectricMaxxx you did the commit (which fixed SF4 issues) but seems to break something else. do you have an idea what is going on here?

**Comment by ElectricMaxxx** [comment]
@webimpress @dbu ohh sorry, did not recognize it. any hints for me to reproduce it?
