### ISSUE TITLE
LocaleListener deprecation with PHP8

### ISSUE THREAD

**Issue by mathieumuller** [lunetics/LocaleBundle#225]
Hi there,

There is a deprecation issue with the constructor of the LocaleListener. The $defaultLocale parameter should not have a default value as it is placed before other required parameters. I am using the bundle with php8.2.1 and Symfony 4 tag 3.0.1RC is the only one I can use for now. Do you think it can be fix, for example this way

```php
 public function __construct(?string $defaultLocale, LocaleGuesserManager $guesserManager, BestLocaleMatcher $bestLocaleMatcher = null, LoggerInterface $logger = null)
    {
        $this->defaultLocale = $defaultLocale ?? 'en';
        $this->guesserManager = $guesserManager;
        $this->bestLocaleMatcher = $bestLocaleMatcher;
        $this->logger = $logger;
    }
```

**Comment by doppiogancio** [comment]
We have the same issue.

**Comment by kamilmusial** [comment]
@mathieumuller Please check out https://github.com/lunetics-org/LocaleBundle/pull/226

**Comment by goetas** [comment]
done in https://github.com/lunetics-org/LocaleBundle/pull/226
