### ISSUE TITLE
Support PHP >= 7.2.5

### ISSUE THREAD

**Issue by hristokpopov** [lunetics/LocaleBundle#230]
Branch 3.x works fine with the following PHP versions >= 7.2.5

I have done some testing with the following fork:
https://github.com/hristokpopov/LocaleBundle/tree/php7

phpunit tests seem to pass as well. A few warnings are generated, but they are not related to the php version.

PHP >= 7.2.5 matches the version needed for Symfony 5.4:
https://symfony.com/releases/5.4

Would it be possible to change the PHP requirement in composer.json to:
"php": ">=7.2.5"

**Comment by goetas** [comment]
if you can create a merge request and make the CI green, I do not see issues with it

**Comment by hristokpopov** [comment]
The PHP requirement was changed to >= 7.2.5:
https://github.com/lunetics-org/LocaleBundle/pull/231
