### ISSUE TITLE
Locale switcher helper can not get languages if request is partial

### ISSUE THREAD

**Issue by Spomky** [lunetics/LocaleBundle#96]
If ```{{ locale_switcher() }}``` is invoked through a partial controller, it can not get available languages and nothing is displayed.

I think that using a ```RequestStack``` object (in Symfony2.4) instead of a ```Request``` object will prevent this bug.
Look at http://symfony.com/blog/new-in-symfony-2-4-the-request-stack

**Comment by ikwattro** [comment]
Fixed by https://github.com/lunetics/LocaleBundle/commit/8afd4b79e1bc24b585ae0a36ae3aebab5b8c87df
